name: Deploy to Firebase & Send Email

on:
  push:
    branches:
      - main

jobs:
  build-deploy-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: imakeflutterapp

      # - name: Send email notification
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: ${{ secrets.EMAIL_USERNAME }}
      #     password: ${{ secrets.EMAIL_PASSWORD }}
      #     subject: "🚀 Firebase Deploy Completed"
      #     to: you@example.com
      #     from: "GitHub Actions <noreply@github.com>"
      #     content_type: text/html
      #     body: |
      #       <h3>🎉 Deployment Success!</h3>
      #       <p>Your Firebase app has been deployed successfully.</p>
      #       <p><a href="https://your-project-id.web.app">Open App</a></p>
