name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: imakeflutterapp
      - name: Send LINE Message via Messaging API
        run: |
          curl -X POST https://api.line.me/v2/bot/message/push \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}' \
          -d '{
            "to": "${{ secrets.LINE_USER_ID }}",
            "messages":[
              {
                "type":"text",
                "text":"🚀 Firebase Deploy Completed Successfully!"
              }
            ]
          }'
